### ISSUE TITLE
CreateEntity doens't handle _id ObjectId 

### ISSUE THREAD

**Issue by l0x539** [moleculerjs/database#11]
https://github.com/moleculerjs/database/blob/ed33d2dcbacb6d3ac8793e0698e1a9c5e71d008d/src/methods.js#L497

I'm not sure if this issue is related to moleculerjs database or another specific package, but Should createEntity handle converting _id string to ObjectId when passing a string _id (similar to mongoose where you can initialize new ObjectId using mongoose.Types.ObjectId())?

For example in this next image, createEntity with _id as string creates an _id string type instead of an ObjectId type, even with using new ObjectId() from mongodb package.

![image](https://user-images.githubusercontent.com/39133551/149136574-634182a1-57af-4f7a-8b0d-e2ab446562a8.png)

**Comment by l0x539** [comment]
https://github.com/moleculerjs/database/blob/ed33d2dcbacb6d3ac8793e0698e1a9c5e71d008d/src/adapters/mongodb.js#L230

For example, the default adapter here handles converting _id, except for insert

**Comment by devalexandre** [comment]
> https://github.com/moleculerjs/database/blob/ed33d2dcbacb6d3ac8793e0698e1a9c5e71d008d/src/methods.js#L497
> 
> I'm not sure if this issue is related to moleculerjs database or another specific package, but Should createEntity handle converting _id string to ObjectId when passing a string _id (similar to mongoose where you can initialize new ObjectId using mongoose.Types.ObjectId())?
> 
> For example in this next image, createEntity with _id as string creates an _id string type instead of an ObjectId type, even with using new ObjectId() from mongodb package.
> 
> ![image](https://user-images.githubusercontent.com/39133551/149136574-634182a1-57af-4f7a-8b0d-e2ab446562a8.png)

try use, ``` findById("") ``` , you are usgin two _id in your find too, for use some ids use ```  '_id': { $in: []} ```

**Comment by icebob** [comment]
Could you create a repro example?
