### ISSUE TITLE
MongoDB Adapter - InsertOne always failing in Mongo Community 4.4

### ISSUE THREAD

**Issue by vimalraj-a** [moleculerjs/database#18]
When mongo adapter connected with local or single node mongo community 4.4 sever, `insertOneResult.acknowledged` is always null. We tried to set writeConcern as 'majority' still failed. But, Same code work with Mongo Atlas with 4.4 version database.

https://github.com/moleculerjs/database/blob/3010c96d5a6efe9931fc9e0f5f52cda182b3de87/src/adapters/mongodb.js#L232

Is there a way to disable the `acknowledged` check in insertOne and insertMany response? @icebob

**Comment by devalexandre** [comment]
@vimalraj-a are you using docker to run?

**Comment by vimalraj-a** [comment]
In production - yes, We are using docker & kubernetes

The problem is when I use it in development with single node mongo community database

**Comment by devalexandre** [comment]
@vimalraj-a , show a docker-compose.yml
