### ISSUE TITLE
empty res after .update collections - 0.2.0 and 0.2.1

### ISSUE THREAD

**Issue by epadilha-add** [moleculerjs/database#72]
I updated to version 0.2.1 and am experiencing the following issue: I no longer receive responses after an update on any collection. I tested the action in isolation and confirmed that there is indeed no return. In my main hook after update, I no longer have a return (res). I tested with versions 0.14.32 and 0.14.35. Only when I revert to version 0.1.1 do I get the responses as expected. My package:

This works!
   "@moleculer/channels": "^0.1.8",
    **"@moleculer/database": "^0.1.1",**
    "@moleculer/lab": "^0.6.2",
    "moleculer": "0.14.35",
    "moleculer-repl": "^0.7.0",  
    "mongodb": "6.11.0",
    "nats": "^1.4.12", 
    "redis": "^3.1.2",
    
  This doesn't work!
   "@moleculer/channels": "^0.1.8",
    **"@moleculer/database": "^0.2.1",**
    "@moleculer/lab": "^0.6.2",
    "moleculer": "0.14.35",
    "moleculer-repl": "^0.7.0",  
    "mongodb": "6.11.0",
    "nats": "^1.4.12", 
    "redis": "^3.1.2",

This is the point where everything happens
![image](https://github.com/user-attachments/assets/160c4a04-e210-4059-bc22-2db199bc5dad)

**Comment by icebob** [comment]
It's strange, because there are test cases which checks the response of update: https://github.com/moleculerjs/database/blob/a72349aa941eab78af83802bf3bd31997d291221/test/integration/actions.test.js#L297-L315

Please create a reproduce example.

**Comment by epadilha-add** [comment]
Thanks icebob. I apologize for not following the script. I will close this thread and open a new one with the reproduction of my problem. Thank you again.
